// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSu3p7K31qkN0cAz9OowsnBUNrPAwml8',
    appId: '1:261565164474:web:945537aef657e9cef8cb83',
    messagingSenderId: '261565164474',
    projectId: 'socialmediaclone-6c860',
    authDomain: 'socialmediaclone-6c860.firebaseapp.com',
    storageBucket: 'socialmediaclone-6c860.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5OIIbuDtmrF58tMOrnN2DGEa5DzLnDdo',
    appId: '1:261565164474:android:6df91bc09570d561f8cb83',
    messagingSenderId: '261565164474',
    projectId: 'socialmediaclone-6c860',
    storageBucket: 'socialmediaclone-6c860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuSvTOa4hjvl8-8L059iwa3bThbqydcE',
    appId: '1:261565164474:ios:41114fc7e7e31530f8cb83',
    messagingSenderId: '261565164474',
    projectId: 'socialmediaclone-6c860',
    storageBucket: 'socialmediaclone-6c860.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuSvTOa4hjvl8-8L059iwa3bThbqydcE',
    appId: '1:261565164474:ios:41114fc7e7e31530f8cb83',
    messagingSenderId: '261565164474',
    projectId: 'socialmediaclone-6c860',
    storageBucket: 'socialmediaclone-6c860.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMSu3p7K31qkN0cAz9OowsnBUNrPAwml8',
    appId: '1:261565164474:web:892a63360070e74bf8cb83',
    messagingSenderId: '261565164474',
    projectId: 'socialmediaclone-6c860',
    authDomain: 'socialmediaclone-6c860.firebaseapp.com',
    storageBucket: 'socialmediaclone-6c860.firebasestorage.app',
  );
}
